---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - wget
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Setup docker user
      ansible.builtin.user:
        name: docker
        groups: "docker"
        append: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-Compose&Set Permission
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Create Docker-Compose symlink
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Create docker directory if it does not exist
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0755'

#    - name: Create Docker-Compose symlink
#      ansible.builtin.command:
#        cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#        creates: /usr/bin/docker-compose

    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
